#!/usr/bin/env bash
# This script is dislaying "Best School" 10 times using while loop
# Displays Best School and then Hi on a new line, on the 9th iteratiom.

i=1
while [ $i -le 10 ];
do
	echo "Best School"

	if [ $i -eq 9 ];
	then
		echo "Hi"
	fi

	(( i++ ))
done
